"""rename department

Revision ID: 597790e0bf02
Revises: a43b18c6f24d
Create Date: 2024-06-26 23:19:00.193427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597790e0bf02'
down_revision = 'a43b18c6f24d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###